apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment-prod
  namespace: prod
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: psrv3/kodekloud_gemini_app # Replace with your image
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-api-key-secret
              key: SECRET_KEY
